--- 
HOST_URL: "<<NOMBRE_SITIO>>.atlassian.net"
USER_EMAIL: "<<USER_EMAIL>>"
API_TOKEN: "<<API_TOKEN>>"
INCLUDE_ATTACHMENTS: "true"
DOWNLOAD_LOCALLY: "true"
UPLOAD_TO_S3:
    AWS_ENDPOINT_URL: "amazon S3 endpoints https://docs.aws.amazon.com/general/latest/gr/s3.html"
    AWS_REGION: "amazon S3 region"
    S3_BUCKET: "S3 bucket name (empty value will skip this step)"
    S3_DIR: "S3 directory for upload (example Atlassian/)"
    AWS_ACCESS_KEY: "not mandatory if already set on the machine with AWS CLI"
    AWS_SECRET_KEY: "not mandatory if already set on the machine with AWS CLI"
    AWS_IS_SECURE: True